### PR TITLE
next integration tests

### PR DESCRIPTION
**Pull request by fpliger**
## Description

This PR moves integration tests out of the old `pyscriptjs` folder 

## Checklist

-   [x] All tests pass locally
-   [ ] I have updated `docs/changelog.md`
-   [ ] I have created documentation for this(if applicable)

### CODE REVIEW

**Review by WebReflection — CHANGES_REQUESTED** [review]
Please add `Makefile` and `environment.yml` to the `.npmignore` file otherwise these files will wrongly end up in CDNs, thank you!

**Comment by fpliger** [comment]
just a heads up @WebReflection . I've removed these files from `pyscript.com` and reused the ones we have on root, so this should be a self-fixed problem :)

**Review by tedpatrick — APPROVED** [review]

**Review by WebReflection — APPROVED** [review]

**Review by tedpatrick — APPROVED** [review]

**Comment by WebReflection** [comment]
FYI I am not sure these are meant to run already but my latest PR didn't run these https://github.com/pyscript/pyscript/pull/1720

**Comment by JeffersGlass** [comment]
When run in the root folder of the project as suggested in `README.md`, `make setup` fails because `environment.yml` is in the `pyscript.js` folder and cannot be found.

**Comment by WebReflection** [comment]
> because environment.yml is in the pyscript.js folder and cannot be found.

that's not in this MR though ... not sure how that made it through :thinking:

**Pull request merged**
