### PR TITLE
Add pys-onInput and pys-onChange events

### PR DESCRIPTION
**Pull request by marianoweber**
Hey,

I saw issue #316 and thought I might create a quick PR to add pys-onInput and pys-onChange events for input elements.
Maybe we should discuss adding a list of all common event types and adding them all in one?

Thanks
Mariano

### CODE REVIEW

**Comment by fpliger** [comment]
@marianoweber yeah, that's a great point. I think this PR adds value on its own already but I'm totally +1 if you'd like to propose a list of the most common event types for discussion. Otherwise, I'm happy to merge as is if you think the PR is ready

**Comment by marianoweber** [comment]
@fpliger
Thank you for reviewing!

Here is a list of possible events (from [https://www.w3schools.com/tags/ref_eventattributes.asp](https://www.w3schools.com/tags/ref_eventattributes.asp)

``` js
// Window Events
        ["pys-onafterprint", "afterprint"],
        ["pys-onbeforeprint", "beforeprint"],
        ["pys-onbeforeunload", "beforeunload"],
        ["pys-onerror", "error"],
        ["pys-onhashchange", "hashchange"],
        ["pys-onload", "load"],
        ["pys-onmessage", "message"],
        ["pys-onoffline", "offline"],
        ["pys-ononline", "online"],
        ["pys-onpagehide", "pagehide"],
        ["pys-onpageshow", "pageshow"],
        ["pys-onpopstate", "popstate"],
        ["pys-onresize", "resize"],
        ["pys-onstorage", "storage"],
        ["pys-onunload", "unload"],

        // Form Events
        ["pys-onblur", "blur"],
        ["pys-onchange", "change"],
        ["pys-oncontextmenu", "contextmenu"],
        ["pys-onfocus", "focus"],
        ["pys-oninput", "input"],
        ["pys-oninvalid", "invalid"],
        ["pys-onreset", "reset"],
        ["pys-onsearch", "search"],
        ["pys-onselect", "select"],
        ["pys-onsubmit", "submit"],

        // Keyboard Events
        ["pys-onkeydown", "keydown"],
        ["pys-onkeypress", "keypress"],
        ["pys-onkeyup", "keyup"],

        // Mouse Events
        ["pys-onclick", "click"],
        ["pys-ondblclick", "dblclick"],
        ["pys-onmousedown", "mousedown"],
        ["pys-onmousemove", "mousemove"],
        ["pys-onmouseout", "mouseout"],
        ["pys-onmouseover", "mouseover"],
        ["pys-onmouseup", "mouseup"],
        ["pys-onmousewheel", "mousewheel"],
        ["pys-onwheel", "wheel"],

        // Drag Events
        ["pys-ondrag", "drag"],
        ["pys-ondragend", "dragend"],
        ["pys-ondragenter", "dragenter"],
        ["pys-ondragleave", "dragleave"],
        ["pys-ondragover", "dragover"],
        ["pys-ondragstart", "dragstart"],
        ["pys-ondrop", "drop"],
        ["pys-onscroll", "scroll"],

        // Clipboard Events
        ["pys-oncopy", "copy"],
        ["pys-oncut", "cut"],
        ["pys-onpaste", "paste"],

        // Media Events
        ["pys-onabort", "abort"],
        ["pys-oncanplay", "canplay"],
        ["pys-oncanplaythrough", "canplaythrough"],
        ["pys-oncuechange", "cuechange"],
        ["pys-ondurationchange", "durationchange"],
        ["pys-onemptied", "emptied"],
        ["pys-onended", "ended"],
        ["pys-onloadeddata", "loadeddata"],
        ["pys-onloadedmetadata", "loadedmetadata"],
        ["pys-onloadstart", "loadstart"],
        ["pys-onpause", "pause"],
        ["pys-onplay", "play"],
        ["pys-onplaying", "playing"],
        ["pys-onprogress", "progress"],
        ["pys-onratechange", "ratechange"],
        ["pys-onseeked", "seeked"],
        ["pys-onseeking", "seeking"],
        ["pys-onstalled", "stalled"],
        ["pys-onsuspend", "suspend"],
        ["pys-ontimeupdate", "timeupdate"],
        ["pys-onvolumechange", "volumechange"],
        ["pys-onwaiting", "waiting"],

        // Misc Events
        ["pys-ontoggle", "toggle"],
```

I changed them to lowercase, as that fits the general HTML casing. The old camel case events should still work, but I can test it if we decide to add this list.

**Comment by fpliger** [comment]
Nice! That's a long list :) 

I don't see a huge drawback in supporting them. This allows a lot of flexibility to users at a relatively low cost.  

The only consideration here (that is not the specific scope of the PR) is that we probably should think if the `pys-` is the right one to consolidate around, instead of aligning with the `py-` we use for components or `pye-` (for py-events).

**Comment by fpliger** [comment]
Closing as superseded since this feature has been added in #561

**Pull request closed without merging**
