### PR TITLE
Changed variable names to snake_case for PEP8 formatting

### PR DESCRIPTION
**Pull request by barnwell**
Changed camelCase variables names to snake_case in order to match PEP8 naming convention.

### CODE REVIEW

**Review by cclauss — APPROVED** [review]

**Review by fpliger — APPROVED** [review]
Thanks @barnwell ! The changes look good. Unfortunately they conflict with the current main since linting and pre-commit have been added in the meantime. If you have some time to fix the conflicts and push, great! Otherwise we'll try to get to it sometime tomorrow. Appreciate your help!

**Comment by barnwell** [comment]
@fpliger Sure thing, I fixed the conflicts. Cheers!

**Comment by fpliger** [comment]
Somehow the latest commit added a weird formatting issue. I fixed it really quick. Merging. Thank you @barnwell !

**Comment by cclauss** [comment]
@barnwell Running https://pypi.org/project/flake8 with the plugin https://pypi.org/project/pep8-naming will help you find a few more to fix.

**Pull request merged**
