### PR TITLE
Use async/await instead of promise chaining

### PR DESCRIPTION
**Pull request by woxtu**
Hi,

This PR changes to use async/await instead of promise chaining to fix [`@typescript-eslint/no-floating-promises`](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-floating-promises.md) warnings.

### CODE REVIEW

**Comment by cclauss** [comment]
pre-commit is complaining that at least one modified line has trailing whitespace.

**Comment by woxtu** [comment]
Hmm... Running pre-commit locally says nothing, and I cannot find the whitespace.

**Comment by cclauss** [comment]
Line 18 of pyscriptjs/src/components/pybutton.ts ?

**Comment by cclauss** [comment]
@mattkram Can you see how we can placate pre-commit?

**Comment by woxtu** [comment]
I'll try merging main for now.

**Comment by woxtu** [comment]
I don't know why, but it seems to pass all checks 🤔

**Comment by mattkram** [comment]
Oh good. I was going to recommend merging in `main`. I can't quite explain the failing state, but I have noticed that `pre-commit` won't run if your branch is not up to date, so it is somehow related to that.

**Review by fpliger — APPROVED** [review]
Thanks for the clean up @woxtu , great! Also thanks for the patience on getting this through :)

**Comment by woxtu** [comment]
@cclauss @mattkram Thanks for your comments!

**Pull request merged**
