### PR TITLE
Added examples demonstrating DOM manipulation

### PR DESCRIPTION
**Pull request by hwuiwon**
Adds a demonstration of a Dom Manipulation, deployed as a web page using Pyscript.

#109

### CODE REVIEW

**Review by renantescaro — APPROVED** [review]

**Comment by fpliger** [comment]
@hwuiwon thanks for the contribution! The intent and overall code look good but I'm not sure this PR actually provides the right guidance to PyScript users on how to manipulate the DOM. The reasons are that:

* PyScript provides an `Element` class that you can use instead of using `document.getElementById` directly. Element has many convenient shortcuts and also access to the original Javascript element (Element.element). So, instead of using `my_div = document.getElementById("myid")` you I'd suggest using `my_div = Element("myid")`.
* I think it'd be more comprehensive to start showing the use of PyScript components or a mix of PyScript components alongside standard HTML (elements) to focus on the simplicity of the framework.
* I'm currently adding and redesigning some of that and I'm afraid this will clash with this example.

For these reasons, I'd hold this example on and wait until I merge additional features related to DOM elements.

**Comment by hwuiwon** [comment]
I see! Thanks for the comments. I'll hold on until the additional features get updated.

**Comment by dkanze** [comment]
Can we or will be soon be able to generate HTML on the fly as can be done with JS?

  async buildValidGameTable(){
    let wordlecontainer = document.getElementById("wordlecontainer")

    let wordledata  = document.createElement("div")
    wordledata.classList.add("wordledata")
    wordlecontainer.appendChild(wordledata);
    wordledata.innerHTML = ''  //Initialize table

    let rows = document.createElement("div")
    rows.classList.add("rows")
    wordledata.appendChild(rows)

    rows.appendChild(this.gameRowHeading())

    for(var game = 0; game < 6; game++){
      let row = this.gameRowBuilder(game)
      rows.appendChild(row)
    }
    let focusoncell = document.querySelectorAll('.gameval')
    focusoncell[0].focus()  // Focus on first cell
  }

**Comment by fpliger** [comment]
@dkanze I'd say, why not? all of the above should be possible

**Pull request closed without merging**
