### PR TITLE
Use Promise.all to fetch files part of py-config

### PR DESCRIPTION
**Pull request by hoodmane**
This is a first step towards loading more stuff simultaneously rather than sequentially.

The functional part of this is pretty small: call `calculateFetchPaths` and then `Promise.all(fetchPaths.map(loadFileFromURL));`. I also transposed the return type of `calculateFetchPaths` since it's more convenient to consume this way.

I redid the logic in `calculateFetchPaths` a bit. I renamed `src/plugins/fetch.ts` to `calculateFetchPaths.ts` since the file performs no fetching. I also renamed `loadFromFile` to `loadFileFromURL`.

### CODE REVIEW

**Comment by WebReflection** [comment]
LGTM 👍

**Review by madhur-tandon — APPROVED** [review]

**Comment by WebReflection** [comment]
@hoodmane is this fixing https://github.com/pyscript/pyscript/issues/1219 ?

**Comment by hoodmane** [comment]
No but it's heading in that direction.

**Comment by hoodmane** [comment]
Thanks for the reviews!

**Pull request merged**
