### PR TITLE
Zip the build folder and add it to release

### PR DESCRIPTION
**Pull request by FabioRosado**
I used `act` to check if this would run successfully (using dry-run) and got a green checkmark, hopefully it will work 😬 

With this PR the `prepare-release` action should zip the `build` folder and include it in the release. There's also an action to zip files/folders, but assuming that `zip` is included in the ubuntu instance, the command should work.

Fixes: #851

### CODE REVIEW

**Comment by madhur-tandon** [comment]
[question] What is `act`?

PS -- Yeah, makes sense to use `zip` since it should be available in the runner instances.

**Review by madhur-tandon — APPROVED** [review]

**Comment by FabioRosado** [comment]
> [question] What is `act`?
> 
> PS -- Yeah, makes sense to use `zip` since it should be available in the runner instances.

`act` allows you to run github actions locally [here's the repo](https://github.com/nektos/act) although while chatting with @pww217 he pointed that a lot of actions expect creds so act wont really work that well (although using dry run seems to be okay)

**Review by pww217 — APPROVED** [review]
Cool - not sure if the runner necessarily has `zip` but it is an Ubuntu base so it probably should. 

If not it's just a quick setup step to install it.

**Comment by pww217** [comment]
Oh actually ignore me this is a public runner

**Comment by FabioRosado** [comment]
Awesome thanks 😄

**Pull request merged**
