### PR TITLE
Update to Codemirror 6 (py-repl)

### LINKED ISSUE #531: Default REPL `indentUnit` to 4
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a duplication
- [X] I already searched in Google and didn't find any good information or help

### What is the issue/comment/problem?

Currently the indent in the REPL is 2 spaces. I propose that this be changed to 4 spaces. This follows [PEP 8](https://peps.python.org/pep-0008/#indentation) and the majority of the examples.

### PR DESCRIPTION
**Pull request by JeffersGlass**
Upgrades CodeMirror to Version 6, released early June, which seems like it'll be [API stable for the foreseeable future](https://marijnhaverbeke.nl/blog/codemirror-6.html).

Also fixes #531 and makes the default indentation on a py-repl 4 spaces, instead of 2.

### CODE REVIEW

**Comment by tedpatrick** [comment]
Awesome, I added this to the release planning list this morning...

"Upgrade to codemirror 6.0.1 from 5.65.3"

**Review by tedpatrick — APPROVED** [review]

**Comment by tedpatrick** [comment]
@JeffersGlass Yours to merge. Rule: You build it you merge it.

**Comment by marimeireles** [comment]
Yesss!
Thank you for this! Months ago I was trying to deal with the old version of codemirror to add new features but it was soo terrible.

**Comment by madhur-tandon** [comment]
Conflicts need to be resolved I guess, then we are good to go!

**Comment by JeffersGlass** [comment]
Good thinking on dynamic loading @madhur-tandon - we might want to do an audit on the packages in general, it looks like `@fortawesome/free-solid-svg-icons` is also pretty heavy. But that's for another PR.

Just like #806 the [pre-commit checks are also failing](https://github.com/pyscript/pyscript/pull/806#issuecomment-1264113803) for me, but I'm going to merge. We should probably figure out what's going on there...

**Pull request merged**
