### PR TITLE
Update to latest Pyodide

### LINKED ISSUE #629: Update Pyodide version to v0.21a2
### Checklist

- [X] I added a descriptive title
- [X] I searched for other feature requests and couldn't find a duplicate (including also the ``type-feature`` tag)
- [X] I confirmed that it's not related to another project area (see the above section)

### What is the idea?

Update Pyodide version to v0.21a2 (or lasted) to enable `exodide` integration with `PyScript`.
The `exodide` team is waiting this `PyScript` update, **as you can see in** [this](https://github.com/ymd-h/exodide/issues/16) link.

### Why is this needed

This will enable easy `PyScript` integration with `C/C++` code compiled to WASM using `exodide`.
`exodide` is easy to use tool to generate WASM and `*.whl` from `C/C++` code.
`exodide` enable `C/C++` users export your functions using `Pybind11` and supports `function overload` and other `C++` features

### What should happen?

In the `PyScript` side, may be is just a dependency update version, but it will enable `exodide` users to compile your `C/C++` code to WASM and `wheel` and use your own packages in `PyScript` environment.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by ntoll**
Initial work (please let me know if this is all I need to do), to update the version of Pyodide we're using. Fixes #629.

### CODE REVIEW

**Comment by ntoll** [comment]
Well, that (CI) went well. An opportunity for me to dig in. :-)

**Comment by marimeireles** [comment]
Yeah, the reason why the CI is failing is because we're pointing the tests to the new `latest` release.
But... I still hadn't the time to check what's up! Maybe @pww217 did?

**Comment by marimeireles** [comment]
Oh and the Push to github project dashboard is because our key is outdated.

**Comment by pww217** [comment]
I've been out of town and am back tomorrow. You're right about the issues
board - it only had a 30 day token.

Haven't been able to look at tests.

**Comment by marimeireles** [comment]
okay, I'll have a look at the failing tests this afternoon =)

**Comment by marimeireles** [comment]
Doesn't seem like this breaks anything.
So I'm merging it. Thanks @ntoll :)

**Review by marimeireles — APPROVED** [review]

**Comment by nyckmaia** [comment]
Hi @marimeireles,
I'm newer in git flow and CI/CD methods...

Could you please help me about how can I get this updated `PyScript` version (which contains the lasted `Pyodide`)?
Here below, the `Exodide` team is trying to use it together with `PyScript`, but without success.

**Exodide Issue:** [https://github.com/ymd-h/exodide/issues/16#issuecomment-1200105600](https://github.com/ymd-h/exodide/issues/16#issuecomment-1200105600)

Can you help us?

Thank you

**Pull request merged**
