### PR TITLE
Apply prettier to css, html, js, md, ts, and yml

### PR DESCRIPTION
**Pull request by hoodmane**
As a followup I will add prettier to the .pre-commit config.
This patch is 100% generated by prettier.
I used a forked version of prettier that understands the
py-script tag.
See https://github.com/hoodmane/pyscript-prettier-precommit
for more info.

### CODE REVIEW

**Comment by hoodmane** [comment]
Huh CI failed with 

> CondaError: Unable to create prefix directory '/home/runner/work/pyscript/pyscript/pyscriptjs/env'.
> Check that you have sufficient permissions.

@FabioRosado is this a flake you've seen before?

**Comment by hoodmane** [comment]
Maybe it means I accidentally commited an env folder...

**Comment by hoodmane** [comment]
Looks like that's the reason, but I'm not sure why the `.gitignore` doesn't cover it. I see:
```.gitignore
# Environments
.env
.venv
env/
venv/
ENV/
```
but `git status` shows `pyscriptjs/env` as an untracked file.

**Comment by hoodmane** [comment]
@FabioRosado would you mind reviewing this? I think it's ready to merge. Note again that all changes are automated.

**Review by FabioRosado — COMMENTED** [review]
Seems like prettier is causing `py-config` to fail since it's adding everything into the same line 😞

**Review by FabioRosado — COMMENTED** [review]
Seems like prettier is causing `py-config` to fail since it's adding everything into the same line 😞

**Comment by hoodmane** [comment]
Oops let me fix.

**Comment by hoodmane** [comment]
I think it's better now.

**Comment by hoodmane** [comment]
@FabioRosado okay can you look at it again now?

**Review by FabioRosado — APPROVED** [review]
Awesome! thank you for putting this in and for the patience 😄

**Comment by hoodmane** [comment]
>  for the patience 😄

Yeah this PR was quite a bit more annoying than I expected. Thanks for the review! (Could you merge? I still have no merge access...)

**Comment by hoodmane** [comment]
Though it might be friendlier to merge #1210 first.

**Comment by hoodmane** [comment]
Huh I'm surprised there weren't conflicts. Thanks again @FabioRosado.

**Comment by cclauss** [comment]
Maybe add `.toml` files?

**Comment by hoodmane** [comment]
> Maybe add .toml files?

What do you mean?

**Comment by cclauss** [comment]
`Apply prettier to css, html, js, md, ts, and yml` ... And also toml files like `pyproject.toml`

**Comment by hoodmane** [comment]
I don't think `prettier` handles toml files:
```
% npx prettier -w pyproject.toml 
[error] No parser could be inferred for file: pyproject.toml
```
There seems to be a prettier-plugin-toml but it says it is in an alpha state and is unmaintained. npm says it has 7,421 downloads per week. Perhaps it's better than nothing? Do you know of any better tool for toml formatting?

**Comment by cclauss** [comment]
Format:
* https://github.com/macisamuele/language-formatters-pre-commit-hooks
* https://github.com/tox-dev/pyproject-fmt

Validate:
* https://github.com/abravalheri/validate-pyproject

**Pull request merged**
