### PR TITLE
[next] Improve config parsing on bootstrap

### PR DESCRIPTION
**Pull request by WebReflection**
## Description

This MR fixes https://github.com/pyscript/pyscript/issues/1700 and it parses any optional *config* **before** anything else gets a chance to happen, using our *error* plugin to show right away errors when the config can't be parsed.

## Changes

  * ditched the basic-toml *polyscript* parser in favor of [a more robust one](https://github.com/WebReflection/toml-j0.4#readme) (~~TBD: is this the one we want to use?~~)
  * checked optional `type` attribute for `py-config` element as extra hint for validation
  * throw correct JSON vs TOML parsing error, when these occur
  * use default robust fetch error when the file is not available
  * show an error when something bad happens while parsing config
  * avoid bootstrapping anything at all (no custom element, no custom type definition) when the entry *config* point can't be parsed
  * smoked tested manually every single use case

## Checklist

-   [x] All tests pass locally
-   [ ] I have updated `docs/changelog.md`
-   [ ] I have created documentation for this(if applicable)

### CODE REVIEW

**Review by antocuni — APPROVED** [review]
That's awesome 😍, thank you!
I have a small additional request, in case it's easy to add (if it's too hard/complicated, probably not worth).

Currently, I get an error like this:
image

In case I have multiple config files, it's not clear where it comes from. Would it be possible to include the URL and/or filename and/or "defined in `<py-config>`" to help the user to understand what is the offending file?

**Comment by WebReflection** [comment]
> In case I have multiple config files, it's not clear where it comes from

that's not supported ... *main* has 1 config, like it is PyScript classic ... it's workers that can have multiple configs ... this is because in main, if you want a plugin (or exclude it) we can't compete with further decisions (it's already in or out) and if you want different packages, we shouldn't ever bootstrap more than once pyodide, so it's rather a matter of documentation than a feature as that would be just chaos on main, while each worker gets its own "world".

That being said, we can add any info we like but wrong URLs will fail due PY0404 errors already, others might show up as message ... that's easy, I can update it.

**Comment by WebReflection** [comment]
@antocuni it's up as URL error when the src is used

**Comment by WebReflection** [comment]
Screenshot from 2023-09-15 12-46-20

**Comment by antocuni** [comment]
awesome! Thank you!

**Pull request merged**
