### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by djchou**
Adding a slack channel to the resources

### CODE REVIEW

**Comment by djchou** [comment]
changing it from slack to discord as a discord channel had already been created.

**Comment by marimeireles** [comment]
Sorry @djchou but I don't think the official community is ready to have a discord channel yet.
Or did something change in the weekend @fpliger?

**Comment by marimeireles** [comment]
For more context please see the reply on the #387. =)

**Comment by fpliger** [comment]
Think you are right @marimeireles . @kevingoldsmith was looking at this but think we focused on documentation and discourse first to prioritize on resources that can be reused. Things are movung really fast and I'd love to avoid confusion/duplication of efforts.

**Comment by kevingoldsmith** [comment]
I'm personally ok with the unofficial Discord channel for the moment.

**Comment by marimeireles** [comment]
Cool, so I thank the initiative @djchou, as I said in the linked comment it's very exciting to see the community forming around pyscript, but for now we won't support discord officially.
Please keep feeling invited to contribute both here, in the [forums](https://community.anaconda.cloud/c/tech-topics/pyscript/41) and in all unofficial communities!
Cheers and thank you once again =)

**Pull request closed without merging**
