### PR TITLE
adding the DNA example

### PR DESCRIPTION
**Pull request by meg-1**
Given one side of a DNA strand, this example returns the other, complementary side of said strand.

### CODE REVIEW

**Review by naschimhit — APPROVED** [review]
Great example

**Comment by meg-1** [comment]
> Great example

thank you!

**Comment by marimeireles** [comment]
Hi @meg-1 thank you for contributing this example :)
Currently we're clustering examples in the collective directory: https://github.com/pyscript/pyscript-collective/
Things are still moving a bit but please make sure to read how to contribute an example and don't hesitate to ping me if something doesn't make sense (also feel free to open an issue there or PR with your opinion), is pretty much community oriented.

**Comment by meg-1** [comment]
> Hi @meg-1 thank you for contributing this example :) Currently we're clustering examples in the collective directory: https://github.com/pyscript/pyscript-collective/ Things are still moving a bit but please make sure to read how to contribute an example and don't hesitate to ping me if something doesn't make sense (also feel free to open an issue there or PR with your opinion), is pretty much community oriented.

hi @marimeireles ! thank you for your answer and feedback on the example :D i created a pull request to the PyScript Collective repository about 4 days ago, but so far there hasn't been any action in the repository towards it. is this because things are still being sorted out and the repository is only starting up??

**Pull request closed without merging**
