### PR TITLE
add config file for pre-commit

### PR DESCRIPTION
**Pull request by pww217**
Simply adds a yaml that tells the Github app for pre-commit to run the Black python linting hook. Add other hooks as required.

This is separate from Github Actions - it runs as an app in the repo/org.

We also runner `prettier` for readme formatting in some repos, as a suggestion.

### CODE REVIEW

**Review by philippjfr — APPROVED** [review]
Looks good to me! I think we agreed to add black formatting but I'll let @fpliger confirm and merge.

**Comment by philippjfr** [comment]
Would also be +1 on adding isort as suggested in https://github.com/pyscript/pyscript/pull/201

**Comment by pww217** [comment]
Alright they have documentation for that but I'm not sure which arguments you'd want to use

https://pycqa.github.io/isort/docs/configuration/pre-commit.html

**Comment by jezdez** [comment]
@pww217 Check out #201, those arguments are reasonable.

**Comment by pww217** [comment]
Alright that seemed to work and isort modified a number of files itself, hence the 10 new file changes.

**Comment by fpliger** [comment]
@pww217 , just a heads up. I've added  an empty precommit file to https://github.com/pyscript/pyscript/pull/231 just to make it pass so I can merge. You'll have conflicts if I merge it to main first.

**Review by fpliger — APPROVED** [review]
lgtm. I'd keep the linted files out of this PR and have a follow up PR (I've done that in my related PR that I just mentioned), mostly for easy of reading... Also, the formatting I added in that PR may clash with this one.. 

Anyway, not a big deal. We can fix later no matter what route you choose. Thank you for this! 💯

**Review by mattkram — APPROVED** [review]
I love it.

I plan to add a few other ones but will do in another PR.

**Pull request merged**
