### PR TITLE
Add syntax highlighting

### PR DESCRIPTION
**Pull request by woxtu**
Hi,

This PR adds syntax highlighting to the `<py-config>` doc.

### CODE REVIEW

**Review by FabioRosado — APPROVED** [review]
Hello @woxtu thank you for this!

**Review by antocuni — APPROVED** [review]
Thank you!

**Comment by antocuni** [comment]
The doc building is failing, maybe it's because it's a PR from a non-maintainer and this it's missing some permission?
@pww217 do you have a clue?

**Comment by madhur-tandon** [comment]
> maybe it's because it's a PR from a non-maintainer and this it's missing some permission?

This is a known issue and affects even the maintainers.

**Review by madhur-tandon — APPROVED** [review]

**Comment by antocuni** [comment]
@madhur-tandon does this mean that we can merge this PR wihout problems?
If so, feel free to merge it, thanks!

**Pull request merged**
