### PR TITLE
Use prettier to format yaml, html, js, and ts

### PR DESCRIPTION
**Pull request by hoodmane**
It seems that there was previously no JavaScript/TypeScript formatter. This adds prettier as a formatter for JavaScript, TypeScript, and yaml. I removed the previous yaml formatter since I think it's better to have prettier do everything.

Five or six of the html files in examples had syntax errors, which I fixed manually.

### CODE REVIEW

**Comment by marimeireles** [comment]
I'm very pro this! :)
Can you please also add docs to it? On how to reproduce your linting. And maybe a command in our makefile for linting stuff.
I started doing it but didn't finish it [here](https://github.com/pyscript/pyscript/pull/1198/files).
I think the docs could probably live on the DEVELOPMENT.md.

**Comment by hoodmane** [comment]
We should use pre-commit. The lint step can be:
```makefile
lint:
	pre-commit run -a
```
Then pre-commit.ci will automatically push fixup commits, the user can install it as a commit hook, etc. Of course it would be worth adding a brief mention in the docs.

It looks like black is already in your precommit config:
https://github.com/pyscript/pyscript/blob/main/.pre-commit-config.yaml#L30-L33

**Comment by hoodmane** [comment]
@marimeireles if you are satisfied with #1244, could you merge that? It's a prereq for this.

**Comment by marimeireles** [comment]
@hoodmane I can merge it, it LGTM, but the way we've been working is someone approves your PR and you merge it yourself :)

**Comment by hoodmane** [comment]
I don't have merge access currently.

**Comment by marimeireles** [comment]
aha, sorry for that. will do then!

**Comment by hoodmane** [comment]
Thanks!

**Comment by hoodmane** [comment]
Closed in favor of #1249.

**Pull request closed without merging**
