### PR TITLE
fixed the logging of initializers

### PR DESCRIPTION
**Pull request by furkandoganktf**
Having same logging message before and after setting initializer creates some confusion and this pr fixes that!

### CODE REVIEW

**Comment by furkandoganktf** [comment]
> Sorry, I don't think I understand what you mean and what you intend to improve with your change. Could you explain it differently maybe?

Updated the description accordingly! To make it clear, having same log before and after the operation creates some confusion and doesn't reflect the actions made it there!

**Comment by marimeireles** [comment]
Ah, I think I understand it now.
In this case I personally don't think this change makes a difference for better understanding. @kathatherine could chime in with a more informed opinion than my non-native English though. What do you think about this wording?

**Comment by kathatherine** [comment]
So, as I understand the file above, the log message is "adding initializer" or "adding post initializer", then the initializer is set, and then the log message would then say "added ..."

Actually, this would probably be helpful, in my opinion. If the log message continues to say "adding" after the initializer is already done, that gives the impression that something is still happening, there's an error or a time out waiting to happen. Changing the messaging seems like a good idea to me, if I'm understanding it correctly.

**Comment by marimeireles** [comment]
Great! Merging then =)
Thank you for the input @kathatherine and for the patience @furkandoganktf!

**Review by marimeireles — APPROVED** [review]

**Pull request merged**
