### PR TITLE
test the testing

### PR DESCRIPTION
**Pull request by pww217**

### CODE REVIEW

**Comment by fpliger** [comment]
@pww217 can you help me understand what's going on here? 😄

**Comment by pww217** [comment]
Oh I'm sorry, it was just to make sure the testing was working as intended after all the changes. I'll close.

**Comment by fpliger** [comment]
No worries, thank you!

**Comment by marimeireles** [comment]
I'll use this to do some testing too...

**Comment by marimeireles** [comment]
Fixes #533

**Comment by marimeireles** [comment]
fixes #533

**Comment by marimeireles** [comment]
closes #533

**Comment by marimeireles** [comment]
Alright, got it.

**Pull request closed without merging**
