### PR TITLE
fixed REPL bugs

### PR DESCRIPTION
**Pull request by marianoweber**
Hey,

I think the play button in the REPL component was misaligned. My commit changes its position from

to

Was the initial alignment intended?

EDIT:
Fixed the auto-generate behavior to correctly remove the auto-generate attribute from generated children. Also added functionality to get the last exec-id and add to that, instead of the root elements exec-id.

### CODE REVIEW

**Comment by marianoweber** [comment]
I also fixed a visual bug after the error output. BUT this is added in the base element (base.ts) and only tested for REPL (works with and without std-err).
Should be tested for other components before merging.

Before:
Animation

After (REPL):
Animation2

After (REPL Advanced):
Animation3

**Comment by chekoduadarsh** [comment]
@marianoweber 
Nice work here, error flushing mechanism is needed.
Linking it to the issue - #358

**Comment by fpliger** [comment]
@marianoweber  thank you for the PR! 🚀   Was holding on reviewing this today because we had some recent bug that could have influenced it... so I wanted to check them first. Will try to review the PR asap.

**Review by fpliger — CHANGES_REQUESTED** [review]
Thanks again @marianoweber  for this work! Really nice. 

I have a couple of very minor comments before we can merge this.

1. As default behaviour, I'd expect output to replace the previous executed output (when pyrepl generates the output element, like in the examples/repl.html) by default instead of stacking results like in the PR. (Ultimately this, like many many other things, should be configurable, but this is not in the scope of this PR)
2. The > icon looks great until the cell grows, then it stays in the middle of the cell (which is not really that convenient). Ideally it'd be good to have it stick in the bottom at the place it starts.... 

Lmk if you are ok to add those changes. I'd love to merge it! Thank you!

**Comment by marianoweber** [comment]
> Thanks again @marianoweber for this work! Really nice.
> 
> I have a couple of very minor comments before we can merge this.
> 
> 1. As default behaviour, I'd expect output to replace the previous executed output (when pyrepl generates the output element, like in the examples/repl.html) by default instead of stacking results like in the PR. (Ultimately this, like many many other things, should be configurable, but this is not in the scope of this PR)
> 2. The > icon looks great until the cell grows, then it stays in the middle of the cell (which is not really that convenient). Ideally it'd be good to have it stick in the bottom at the place it starts....
> 
> Lmk if you are ok to add those changes. I'd love to merge it! Thank you!

Thanks for your feedback! Those are very good points.
I will add the changes and create a commit in a moment.

**Comment by marianoweber** [comment]
@fpliger 
changed the CSS part:
Animation4

Regarding the other problem:
It looks like the REPL was always appending, I never changed anything regards that behavior. If you could please take a look at [https://pyscript.net/examples/repl.html](https://pyscript.net/examples/repl.html) and confirm that?

And that is a completely different and more complex problem, as the `append` property gets passed through multiple methods down to the `Element`, `PyScript`, `OutputManager` and finally `OutputCtxManager` in `pyscript.py`.
Somewhere on the way it gets set to true by default. I am currently trying to figure out in which order the output gets passed through the 3 different `write` methods... 🤯

**Comment by fpliger** [comment]
That's awesome and looks great, thank you @marianoweber ! 

In regards of append, that might very well be. I somehow thought we fixed that but probably not. At this point , I'd be +1 on merging it as is and open a new issue for the related repl append issue.

**Review by fpliger — APPROVED** [review]
🚀🚀🚀

**Pull request merged**
