### PR TITLE
version number in build

### PR DESCRIPTION
**Pull request by tedpatrick**

### CODE REVIEW

**Comment by fpliger** [comment]
pinging @FabioRosado as a pin for us to keep in mind for the nest release

**Comment by antocuni** [comment]
there must be a better way to automatically get it from the git tag, mustn't it?

**Review by fpliger — APPROVED** [review]
Great! 🚀  

now go 

Alt Text

**Comment by fpliger** [comment]
@antocuni there is. Ted mentioned it was getting too complicated. FWIW, manual is better than none and does the job alright

**Comment by tedpatrick** [comment]
Infinity better than "<<VERSION>>"

**Comment by antocuni** [comment]
> Ted mentioned it was getting too complicated. FWIW, manual is better than none and does the job alright

sure, I wasn't proposing to do it *now*. This PR is fine, but would be nice to have the more automated way eventually

**Comment by tedpatrick** [comment]
I had to turn on Rollup JSON injection, then TS complained, then tests broke, then, then, then.

**Pull request merged**
