### PR TITLE
pre-commit: Try to autofix yaml BEFORE checking it

### PR DESCRIPTION
**Pull request by cclauss**
Also fixes an issue where `check-yaml` was being run twice.

### CODE REVIEW

**Comment by mattkram** [comment]
Good catch on `check-yaml`.

Regarding the ordering of reformat and check yaml, I'm not convinced this would actually change anything. Can you share an example?

My skepticism is that, even if the yaml files are reformatted before the `check-yaml` hook is run, they are not restaged and thus `pre-commit` will fail anyway.

If that is the case, then personally I prefer to keep the "official" hooks at the top of the file for aesthetic reasons.

**Comment by cclauss** [comment]
I spotted the problem here https://results.pre-commit.ci/run/github/461710233/1651873302.QTUN1cNZROSpFTt5YjKXiA

**Comment by mattkram** [comment]
> I spotted the problem here https://results.pre-commit.ci/run/github/461710233/1651873302.QTUN1cNZROSpFTt5YjKXiA

Looks like that error in particular was caused by the use of the symbol "*" without quotes, and unrelated to ordering.

Let's just remove the duplicate `check-yaml` and move the `check-json` up to be with its siblings for now.

**Review by mattkram — APPROVED** [review]
🚀 Thanks @cclauss!

**Pull request merged**
