### PR TITLE
Create README_CN.md

### PR DESCRIPTION
**Pull request by Grey-Wind**
## Description

add a Chinese readme file

## Checklist

-   [x] All tests pass locally
-   [x] I have updated `docs/changelog.md`

### CODE REVIEW

**Comment by Grey-Wind** [comment]
Maybe I will translate more things tomorrow

**Comment by Grey-Wind** [comment]
Did anyone can review this to request?

**Comment by Grey-Wind** [comment]
I promise all is right.

**Comment by WebReflection** [comment]
@Grey-Wind this is a lovely contribution but we're going to release *PyScript Next* soon so that this documentation in particular would be replaced / deprecated and it's probably not worth a deploy right now ... happy to hear from others too though /cc @fpliger @FabioRosado @ntoll @antocuni

**Comment by Grey-Wind** [comment]
> @Grey-Wind this is a lovely contribution but we're going to release _PyScript Next_ soon so that this documentation in particular would be replaced / deprecated and it's probably not worth a deploy right now ... happy to hear from others too though /cc @fpliger @FabioRosado @ntoll @antocuni

OK，Maybe I can' translate it when PyScript Next publish.

**Comment by fpliger** [comment]
That'd be absolutely amazing. 

I think that, as we try to do that after we release Next, we should also think about a process to maintain translations and signal when a version of the docs hasn't been translated (as we can't always guarantee to have volunteers keeping translations up to date)

**Pull request closed without merging**
