### PR TITLE
import create_proxy and to_js from pyodide.ffi

### PR DESCRIPTION
**Pull request by madhur-tandon**

### CODE REVIEW

**Review by philippjfr — APPROVED** [review]
Looks good!

**Comment by marimeireles** [comment]
Thanks @madhur-tandon!
Unfortunately I'm still seeing the error when I run the `antigravity` example.
We're probably using somewhere else in the code?

**Comment by madhur-tandon** [comment]
> Unfortunately I'm still seeing the error when I run the `antigravity` example.

Try in a private window / incognito mode, it might be cached for you.
Also, re-run `make examples` after pulling from `main`

**Comment by marimeireles** [comment]
Was just local 👍
It's working fine. Thanks @madhur-tandon

**Pull request merged**
