### PR TITLE
Fix `<py-repl theme="dark">`

### PR DESCRIPTION
**Pull request by imjul1an**
`<py-repl theme='dark'>` will result in rendering a dark theme.

Screenshot 2022-05-10 at 18 07 20

### CODE REVIEW

**Review by fpliger — CHANGES_REQUESTED** [review]
The change looks great. Thanks @imjul1an !! The only thing missing is to copy that attribute over when we create a new REPL when the repl itself has the autogenerate=true. Basically you need to add that to lines 172. (if you try the repl in dark theme you'll see that the 2nd one, after you executed, doesn't carry the theme)

**Comment by imjul1an** [comment]
Got it! Will added it!

**Comment by imjul1an** [comment]
@fpliger 

Screenshot 2022-05-11 at 14 37 57

**Review by fpliger — APPROVED** [review]
awesome! Thanks @imjul1an !

**Pull request merged**
