### PR TITLE
Fix event handling issue

### LINKED ISSUE #420: PyButton raises exception
**Describe the bug**
Clicking on a PyButton produces:

```
pyproxy.gen.ts:237 Uncaught Error: This borrowed proxy was automatically destroyed at the end of a function call. Try using create_proxy or create_once_callable.
The object was of type "function" and had repr "<function on_click_sample_btn at 0x13a8938>"
    at _getPtr (pyproxy.gen.ts:237:11)
    at PyProxyClass.apply (pyproxy.gen.ts:1145:32)
    at Object.apply (pyproxy.gen.ts:1022:18)
```

And does not execute the code.

**To Reproduce**
Go to https://twiecki.io/pymc-in-browser.html and click sample.

**Expected behavior**
One or two days ago this was working fine. I suspect maybe this PR to the culprit: https://github.com/pyscript/pyscript/pull/400

Context: https://github.com/pyscript/pyscript/pull/398

### PR DESCRIPTION
**Pull request by woxtu**
Hi,

This PR fixes the process of adding event listeners to fix #420.

### CODE REVIEW

**Review by yannickfunk — APPROVED** [review]
LGTM! Thank you for fixing

**Comment by marimeireles** [comment]
Hey @yannickfunk and @woxtu I tried locally with the `todo-pylist.html` example.
Could you please test it too and confirm the issue is still happening?
@yannickfunk that's all you did to fix it? 
The issue described on #420 persists exactly the same for me.

**Comment by yannickfunk** [comment]
@marimeireles for me `todo-pylist.html` works fine with the changes of this `PR`. Did you think of changing the pyscript.js tag to the local build when testing?

**Comment by marimeireles** [comment]
@yannickfunk yes, I'm using the right path. But I think before I had a cache problem. Sorry for that.

I cleaned my cache and I'm getting two errors now, the first one when I load the page:

```
base.ts:208 Uncaught (in promise) TypeError: this.proxyClass is not a function
```

The second one every time I click the button to try to add a new task (but get an error instead of any graphic result):

```
pyodide.asm.js:14 Uncaught PythonError: Traceback (most recent call last):
  File "<exec>", line 2, in on_click_new_task_btn
  File "<exec>", line 3, in add_task
NameError: name 'dt' is not defined
```

I wonder if it's just something local? If you can't reproduce maybe @woxtu could be our sanity test?
Thanks!

**Comment by yannickfunk** [comment]
@marimeireles seems like it fails to resolve `dt` in your case. Is your utils.py in the examples folder alright?

**Comment by marimeireles** [comment]
Hey @yannickfunk, everything was in the right place.
Seems like `npm` was generating a weird/wrong bundle for me though, because as soon as I restarted it it worked for me. (Fabio talked about this earlier, how `npm run dev` is generating different bundles, maybe it's even related to #427?)
I'll merge this PR as for my understanding this change is all it takes to fix the issue :)
Thanks for the sanity test @yannickfunk!

**Review by marimeireles — APPROVED** [review]

**Comment by yannickfunk** [comment]
@marimeireles yeah could be, I always restart npm run dev to make sure changes are applied

**Comment by woxtu** [comment]
@yannickfunk @marimeireles Thanks for your help!

**Comment by djchou** [comment]
https://pyscript.net/alpha/pyscript.js isnt updated for these changes.  How does that file get updated?

**Comment by yannickfunk** [comment]
@djchou It will be updated with the next release of pyscript. See https://github.com/pyscript/pyscript/issues/449#event-6710460770

**Pull request merged**
