### PR TITLE
Revert changes to the sync workflow

### PR DESCRIPTION
**Pull request by FabioRosado**

### CODE REVIEW

**Comment by marimeireles** [comment]
Why are we doing this?
Is it still relevant to fix the weekend bug?

**Comment by FabioRosado** [comment]
Because for the fix in the weekend I had to add that line in the workflow. we should revert these changes.

**Review by marimeireles — APPROVED** [review]
Thanks!

**Comment by FabioRosado** [comment]
Thank you 😄

**Pull request merged**
