### PR TITLE
Added pyscript and django-rest example

### PR DESCRIPTION
**Pull request by steelthedev**
Created A simple to-do app with pyscript and Django rest framework. A good example that shows the use of pyfetch and the pythonic way of writing javascript.

### CODE REVIEW

**Comment by marimeireles** [comment]
Hi @steelthedev that's a super cool example! :)
For organizational reasons we're moving most examples to https://github.com/pyscript/pyscript-collective 
Can you please add the PR there?
Cheers and thanks once again for the great contribution!
cc: @papotte you might be interested in this work.

**Comment by steelthedev** [comment]
Alright, I just added the PR to the mentioned repo

**Comment by steelthedev** [comment]
@tedpatrick done that for a while now.

**Comment by tedpatrick** [comment]
Starting is hard and we are just now ironing out the process and direction. We had a long delay in approving @pauleveritt work on the Collective, and we are working through project cleanup and testing. Again, I really appreciate your patience and contribution.

**Pull request closed without merging**
