### PR TITLE
Updated Polyscript to its latest

### PR DESCRIPTION
**Pull request by WebReflection**
## Description

This MR fixes https://github.com/pyscript/pyscript/issues/2035 by bringing in the latest *polyscript* library with fixes around *MicroPython* *untar* and *unzip*.

## Changes

  * update *polyscript* to its latest
  * updated other dev dependencies to keep dependencies updated

## Checklist

-   [x] All tests pass locally
-   [ ] I have updated `CHANGELOG.md`
-   [ ] I have created documentation for this(if applicable)

### CODE REVIEW

**Comment by WebReflection** [comment]
@ntoll this module has been published already to *npm*

  * JS via https://cdn.jsdelivr.net/npm/@pyscript/core@0.4.22/dist/core.js
  * CSS via https://cdn.jsdelivr.net/npm/@pyscript/core@0.4.22/dist/core.css

Feel free to test your use case by providing those CDN end points until we release officially, thanks.

**Review by fpliger — APPROVED** [review]
👍

**Comment by WebReflection** [comment]
I'll keep this on hold until MicroPython latest with code length fixes land on *npm* if this happens today, otherwise I'll merge it for the sake of the release ... it'd be super cool to have that fix landed though!

**Comment by ntoll** [comment]
Agreed that having latest MicroPython would be best. cc/ @dpgeorge

**Comment by dpgeorge** [comment]
I aim to update MicroPython now.

**Pull request merged**
