### PR TITLE
Add prettier to pre-commit

### PR DESCRIPTION
**Pull request by hoodmane**
This uses my forked version of prettier. Prettier has no API to ask it to leave `py-script` and `py-config` alone, but it does have an internal method.
See my precommit hook here: https://github.com/hoodmane/pyscript-prettier-precommit

@FabioRosado It would be better to rebase-merge / merge-merge this and not to squash merge, since commit 2 is 378 lines of automated changes (another option would be to split into two prs and temporarily disable pre-commit.ci between them, but that's more annoying)

### CODE REVIEW

**Comment by hoodmane** [comment]
On top of #1256.

**Comment by hoodmane** [comment]
@madhur-tandon could you review this now?

**Review by madhur-tandon — APPROVED** [review]
LGTM

**Comment by hoodmane** [comment]
I suppose it's important to point out that this uses my forked version of prettier. Prettier has no API to ask it to leave `py-script` and `py-config` alone, but it does have an internal method.
See my precommit hook here: https://github.com/hoodmane/pyscript-prettier-precommit

**Pull request merged**
