### PR TITLE
Use a recommended method

### PR DESCRIPTION
**Pull request by woxtu**
Hi,

This PR changes `onXYZ()` to recommended `addEventListener()`.

https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener

### CODE REVIEW

**Review by verhulstm — APPROVED** [review]
thinks makes sense to me

thanks :)

**Review by fpliger — APPROVED** [review]
@woxtu thank you! This looks great. It's currently conflicting with recent changes in main. Would you mind fixing them so i can merge it? 

Thank you!

**Comment by woxtu** [comment]
@fpliger Thank you! It's ready to merge!

**Comment by fpliger** [comment]
Awesome. Thanks again @woxtu !

**Pull request merged**
