### PR TITLE
Added code in todo.py 

### PR DESCRIPTION
**Pull request by NitishKumar06**
In this commit, I've added code in the todo.py which was initially empty. Since this file was being used in the todo.html , Whenever I used to click on this file, the empty file used to make me think what's the purpose of this file here if no code has been written in Java. Please review the code changes and suggest changes if necessary

### CODE REVIEW

**Comment by fpliger** [comment]
@NitishKumar06 Thanks for your interest in PyScript and for contributing to it! I'm not sure I understand what this PR is doing. It seems like you are adding a todo.py that should run with standard CPython on the user's laptop and not in PyScript itself. Right? I'd expect your changes to not run in PyScript at all.

Can you give some more context?

**Comment by NitishKumar06** [comment]
@fpliger In the To-do list .html , todo.py was mentioned in the pyscript tag which was redirecting to the code of todo.py But when I go that todo.py, it was completely empty and that's why I added the code in the todo.py so that when a contributor clicks on todo.py, there should be a code which helps him understand what exactly is todo.py is doing.

**Comment by antocuni** [comment]
@NitishKumar06 I think there is a big misunderstanding here.
You say that "todo.py was initially empty" but that's not true: it is present in the in `pyscriptjs/examples`, alongside `todo.html`. These are the first lines:
https://github.com/pyscript/pyscript/blob/71319d09690196c5a6ce7be667bbcb77d7ebed2d/pyscriptjs/examples/todo.py#L1-L5

Your commit adds a `todo.py` to the root of the repo, which is conceptually wrong. Moreover, it's Tkinter code which is completely unrelated to PyScript.

I fear this PR should be marked as invalid.

**Comment by fpliger** [comment]
Per the conversation above, closing and tagging as invalid. @NitishKumar06 please feel free to chime at any time if you think we are missing context. TY

**Pull request closed without merging**
