### PR TITLE
fix tests by changing serving dir

### PR DESCRIPTION
**Pull request by madhur-tandon**

### CODE REVIEW

**Comment by marimeireles** [comment]
They were failing before?

**Comment by madhur-tandon** [comment]
> They were failing before?

yup, because `make examples` didn't work on Linux and because of that, CI was giving an illusion of everything passing.

**Comment by marimeireles** [comment]
Alright, let me check it locally on a clean branch :)
Juuust to be suuureee 🥸

**Comment by marimeireles** [comment]
Hey @madhur-tandon, I'm getting this locally:

```
=================================== FAILURES ===================================
________________________ test_examples[chromium-folium] ________________________

example = 'folium', http_server = 'http://127.0.0.1:8080'
page = <Page url='http://127.0.0.1:8080/examples/folium.html'>

    @pytest.mark.parametrize("example", EXAMPLES)
    def test_examples(example, http_server, page):
        base_url = http_server
        example_path = urljoin(base_url, TEST_PARAMS[example]["file"])

        page.goto(example_path, wait_until="commit")

        title = page.title()

        # STEP 1: Check page title proper initial loading of the example page
        expected_title = TEST_PARAMS[example]["title"]
        if isinstance(expected_title, list):
            # One example's title changes so expected_title is a list of possible
            # titles in that case
            assert title in expected_title  # nosec
        else:
            assert title == expected_title  # nosec

        # STEP 2: Test that pyodide is loading via messages displayed during loading
        wait_for_load(page)

        # Step 3: Wait for expected pattern to appear on page
>       wait_for_render(page, "*", TEST_PARAMS[example]["pattern"])

tests/test_examples.py:211:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

page = <Page url='http://127.0.0.1:8080/examples/folium.html'>, selector = '*'
pattern = '<iframe srcdoc='

    def wait_for_render(page, selector, pattern):
        """
        Assert that rendering inserts data into the page as expected: search the
        DOM from within the timing loop for a string that is not present in the
        initial markup but should appear by way of rendering
        """
        re_sub_content = re.compile(pattern)
        py_rendered = False  # Flag to be set to True when condition met

        for _ in range(TEST_ITERATIONS):
            content = page.inner_html(selector)
            if re_sub_content.search(content):
                py_rendered = True
                break
            time.sleep(TEST_TIME_INCREMENT)

>       assert py_rendered  # nosec
E       assert False

tests/test_examples.py:186: AssertionError
----------------------------- Captured stderr call -----------------------------
127.0.0.1 - - [02/Aug/2022 13:46:47] "GET /examples/folium.html HTTP/1.1" 200 -
127.0.0.1 - - [02/Aug/2022 13:46:47] "GET /build/pyscript.css HTTP/1.1" 200 -
127.0.0.1 - - [02/Aug/2022 13:46:47] "GET /build/pyscript.js HTTP/1.1" 200 -
________________________ test_examples[chromium-panel] _________________________

example = 'panel', http_server = 'http://127.0.0.1:8080'
page = <Page url='http://127.0.0.1:8080/examples/panel.html'>

    @pytest.mark.parametrize("example", EXAMPLES)
    def test_examples(example, http_server, page):
        base_url = http_server
        example_path = urljoin(base_url, TEST_PARAMS[example]["file"])

        page.goto(example_path, wait_until="commit")

        title = page.title()

        # STEP 1: Check page title proper initial loading of the example page
        expected_title = TEST_PARAMS[example]["title"]
        if isinstance(expected_title, list):
            # One example's title changes so expected_title is a list of possible
            # titles in that case
            assert title in expected_title  # nosec
        else:
            assert title == expected_title  # nosec

        # STEP 2: Test that pyodide is loading via messages displayed during loading
        wait_for_load(page)

        # Step 3: Wait for expected pattern to appear on page
>       wait_for_render(page, "*", TEST_PARAMS[example]["pattern"])

tests/test_examples.py:211:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

page = <Page url='http://127.0.0.1:8080/examples/panel.html'>, selector = '*'
pattern = '<div.*?class=[\'"]bk-root[\'"].*?>'

    def wait_for_render(page, selector, pattern):
        """
        Assert that rendering inserts data into the page as expected: search the
        DOM from within the timing loop for a string that is not present in the
        initial markup but should appear by way of rendering
        """
        re_sub_content = re.compile(pattern)
        py_rendered = False  # Flag to be set to True when condition met

        for _ in range(TEST_ITERATIONS):
            content = page.inner_html(selector)
            if re_sub_content.search(content):
                py_rendered = True
                break
            time.sleep(TEST_TIME_INCREMENT)

>       assert py_rendered  # nosec
E       assert False

tests/test_examples.py:186: AssertionError
----------------------------- Captured stderr call -----------------------------
127.0.0.1 - - [02/Aug/2022 13:48:06] "GET /examples/panel.html HTTP/1.1" 200 -
127.0.0.1 - - [02/Aug/2022 13:48:06] "GET /build/pyscript.css HTTP/1.1" 200 -
127.0.0.1 - - [02/Aug/2022 13:48:06] "GET /build/pyscript.js HTTP/1.1" 200 -
=========================== short test summary info ============================
FAILED tests/test_examples.py::test_examples[chromium-folium] - assert False
FAILED tests/test_examples.py::test_examples[chromium-panel] - assert False
=================== 2 failed, 18 passed in 236.17s (0:03:56) ===================

make: *** [test] Error 1
```

Have you tried the tests locally? Do they run fine for you in your M1?

**Comment by marimeireles** [comment]
I mean, I don't see how these changes would affect these two tests anyway, I guess... So we might just want to merge it.
I'm mainly curious if this is happening to you too. I had a ton of issues last week while working with tests.

**Comment by madhur-tandon** [comment]
> I'm mainly curious if this is happening to you too.

All of them pass locally for me.

**Comment by marimeireles** [comment]
This doesn't help. I've tested with several different time constraints variations.
I wonder if it's my internet who's been pretty bad since I came back :(
I'm a +1 for merging this if it works locally for you and if it's a blocker for your work.

**Review by marimeireles — APPROVED** [review]

**Comment by madhur-tandon** [comment]
> I'm a +1 for merging this if it works locally for you and if it's a blocker for your work.

It works locally as well as on the CI too as seen by the passed checks. Thanks for approving.

**Comment by marimeireles** [comment]
Okay, sorry for that I forgot to approve.
But! The interesting thing is that now I'm in a place with good internet and the tests just ran super fine!

**Pull request merged**
