### PR TITLE
Add tests for changes to examples/

### PR DESCRIPTION
**Pull request by FabioRosado**
This PR updates our CI job to run on changes to `examples/` as well, initially I was a bit concerned about running the push to s3, but it seems that `s3 sync` will only copy files if they have been changed, if we changed only the examples, nothing should be copied.

Also, initially I created a separate CI job to run on changes to examples (run tests only), but then realised that if we create a PR with changes to both `examples` and `pyscriptjs` then we would be running the same CI twice (with the exception of pushing to s3)

### CODE REVIEW

**Review by madhur-tandon — APPROVED** [review]
I guess you could just change the comments that state it only runs under `pyscriptjs` and then we are ready to go!

**Comment by madhur-tandon** [comment]
> initially I was a bit concerned about running the push to s3, but it seems that `s3 sync` will only copy files if they have been changed, if we changed only the examples, nothing should be copied.

If you notice the `path` parameter in the upload action, it's `pyscriptjs/build` -- so `examples` won't be uploaded anyway.

**Comment by FabioRosado** [comment]
Yeah, but that part of the CI should still run if we change only the examples right?

**Comment by madhur-tandon** [comment]
> Yeah, but that part of the CI should still run if we change only the examples right?

Yup, I thought you were talking about uploading of `examples`, my bad 😅

**Pull request merged**
