### PR TITLE
update README.md and CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by jaynarayan-vaishnav**
Corrected the grammatical mistakes to make the documents easier to read and understand.

### CODE REVIEW

**Comment by jaynarayan-vaishnav** [comment]
@jezdez  can you please review this PR.

**Review by fpliger — CHANGES_REQUESTED** [review]
@jaynarayan-vaishnav thank you for your contribution! I'm not sure the change adds to the message in this part of the documentation. I checked the text with a tech writer and the change from "to" to "of" seems off in this context. Also, I wouldn't add "any".. I don't feel like we can claim that honestly (although our goal may be in that direction).

I would keep the change to remove that one comma after "hackable". :) 

Happy to be convinced otherwise, or to merge if you are ok with the above comments. TY!

**Comment by jaynarayan-vaishnav** [comment]
Do you mean that the corrections are unnecessary with respect to the context of this document? and i have to change it to how it was before? I agree with the removal of ```,``` after hackable. I am sorry if I got your explanation in the wrong way @fpliger .

**Comment by fpliger** [comment]
Oh, nothing to be sorry about :) , your help is much appreciated!

Yeah, I mean that I'd revert to how it was before and just change the `'`.  So, basically, final version be:

```PyScript is a Pythonic alternative to Scratch, JSFiddle, or other "easy to use" programming frameworks, making the web a friendly, hackable place where anyone can author interesting and interactive applications.```

**Comment by jaynarayan-vaishnav** [comment]
okay, I got Your Point thanks for helping me. 😄 and can you also check the comments in #61 that I made after the PR got merged as kathatherine said I should create a new issue or directly make a PR . can you suggest to me what should I do about that it would be really helpful

**Comment by fpliger** [comment]
You can open a PR directly linking to the discussion you mentioned above or do it here, both are fine ways. If it was a big change I'd recommend opening a new issue/pr but seems a pretty limited change... 👍

**Comment by jaynarayan-vaishnav** [comment]
I have merged both the issues in the same PR. can you please Review it

**Comment by jaynarayan-vaishnav** [comment]
@fpliger  can you please review this PR.

**Comment by fpliger** [comment]
@jaynarayan-vaishnav was looking at this just right now. I think we can merge the changes if you'd like to re-open it.

**Comment by jaynarayan-vaishnav** [comment]
@fpliger   while i was fetching upstream there were some merge conflicts i will resolve them then reopen this PR if it's okay with you.

**Comment by jaynarayan-vaishnav** [comment]
I've resolved  the merge conflict and opening the PR again. Please review it @fpliger

**Comment by jaynarayan-vaishnav** [comment]
Hey @fpliger can you please review this otherwise there might be some conflicts like in the previous PR. Sorry for disturbing you time and again.

**Review by fpliger — APPROVED** [review]

**Pull request merged**
