### PR TITLE
Fix test and add new ones to close 878

### LINKED ISSUE #878: display() sends the output to the wrong tag
`<rant>`
During the infinite discussion in https://github.com/pyscript/pyscript/issues/769 we decided to use a "dynamic" implicit target for `display()`, which as far as I know can be only implemented with a global variable.

I am [still convinced](https://github.com/pyscript/pyscript/pull/749#discussion_r995734547) that this approach is very fragile and it will create tons of problems and nasty and subtle bugs.
I predict this is the first of many :crystal_ball:

We are still in time to change our minds.
`</rant>`

I found this problem during an unrelated refactoring. I think I know what happens but I don't want to solve it now, so I'm writing an issue to make sure we don't forget.
Consider this test:
```python
        self.pyscript_run(
            """
            <py-script>
                display('hello 1')
            </py-script>
            <p>hello 2</p>
            <py-script>
                display('hello 3')
            </py-script>
        """
        )
```

It displays `hello 2, hello 1, hello 3`:
image

I think the bug was introduce by PR #749 but the roots of the bug are much deeper than this and shows some criticality on our code base.

To start with, the current test that we have is suboptimal:
https://github.com/pyscript/pyscript/blob/aa85f5f5964e61f47b77cac73511d3d74c63328d/pyscriptjs/tests/integration/test_02_output.py#L19-L38

it seems to test for the right thing, but because of the mess that we do when generating outputs, the test passes "by chance". The problem is that to display outputs we create `<div>`s inside `<div>`s inside `<div>`s, each with a random ID, which makes everything very hard to test. We should improve testability of such a simple thing. This will hopefully be solved as part of the PR I'm working on.

The other problem is much deeper. I *think* that the root cause is here:
https://github.com/pyscript/pyscript/blob/aa85f5f5964e61f47b77cac73511d3d74c63328d/pyscriptjs/src/components/base.ts#L119-L124

The thing to note is that `Runtime.run` is `async`, so the three calls are not executed in strict order. I think that what happens is roughly the following:
1. `main.ts` starts to execute the first py-script. We run `set_current_display_target(FIRST_TAG)`, but since it's `async` we immediately interrupt the execution
2. `main.ts` starts to execute the second py-scritp. We run `set_current_display_target(SECOND_TAG)`.
3. at some point in the future we execute the rest of the `run()`, but now the "current display target" is always `SECOND_TAG`.

The proper fix is to ensure that the three calls are done atomically, but it's very hard to to it reliably.
A quick&dirty fix is probably to concatenate the three strings into one big string, but it's a very slipper slope. It might work right now because we execute everything in the global namespace (and we shouldn't) and it will break as soon as we stop doing it (e.g. to implement custom namespaces).

Another "maybe fix" is to use the famous `ContextVar`, but AFAIK it's a python-only thing. I don't really know how it interacts with the JS event loop and I think we should be very cautious before using it without *fully* understanding how it works in pyodide.

Another possible fix is to use *synchronous* calls to `run`: this probably solves the problem, but it breaks all `py-script` tags which uses `await` at top level. FWIW, this is one more data point which indicates that maybe they should not be allowed.
Note that currently we don't have any way to run pyodide code synchronously, which should probably kill `Runtime.run` and introduce `Runtime.runSync` and `Runtime.runAsync`.

### PR DESCRIPTION
**Pull request by marimeireles**
Fixed the tests that were xfail or failing + added a new test to make @antocuni happy.
Intends to close #878

### CODE REVIEW

**Review by antocuni — APPROVED** [review]
> Fixed the tests that were xfail or failing + added a new test to make @antocuni happy. Intends to close #878

😂😂😂
It's not to make me happy, it's to make the codebase better ;).

Ah right, I didn't remember that we had already a test marked as `xfail`: good! But I also like the new test, good :muscle:

**Comment by marimeireles** [comment]
I need to pre commit it 😅
Alright, of course is to make the code base better but I have to be honest and say that 50% of the reason why I added it was because I thought you'd like it.

**Comment by madhur-tandon** [comment]
Is this waiting on the CI to pass? If yes, I think https://github.com/pyscript/pyscript/pull/978 fixes it.
Maybe @marimeireles we can wait for that to be merged and then you can rebase on `main` for this PR.

**Comment by marimeireles** [comment]
Thanks @madhur-tandon will try now! ;)

**Comment by marimeireles** [comment]
Ah no, I guess it's something else.
Will address it now.

**Comment by marimeireles** [comment]
Okay. I have no idea why this is failing.
I don't think it's related to what I'm doing here, it's prbb smth else.
Specially cause it was green before and now it's red.
So... maybe #978 didn't properly fix?

**Comment by FabioRosado** [comment]
I'm not sure why but I had to rebase main into my other branch for the tests to pick up the changes

**Comment by marimeireles** [comment]
Interesting, alright =)

**Comment by marimeireles** [comment]
Ah, well cause it's running from the previous yamls
Makes sense 😅

**Pull request merged**
